tools/testing/selftests/x86: fix error: conflicting types for 'pkey_get|pkey_set'
pkey_get() and pkey_set() are implemented since glibc-2.27, here just
rename pkey_get|pkey_set to _pkey_get|_pkey_set simply

the compiling errors are like:
------------
protection_keys.c:399:5: error: conflicting types for 'pkey_get'
 u32 pkey_get(int pkey, unsigned long flags)
     ^
In file included from /usr/include/bits/mman-linux.h:115:0,
                 from /usr/include/bits/mman.h:45,
                 from /usr/include/sys/mman.h:41,
                 from protection_keys.c:37:
/usr/include/bits/mman-shared.h:64:5: note: previous declaration of 'pkey_get' was here
 int pkey_get (int __key) __THROW;
     ^
protection_keys.c:421:5: error: conflicting types for 'pkey_set'
 int pkey_set(int pkey, unsigned long rights, unsigned long flags)
     ^
In file included from /usr/include/bits/mman-linux.h:115:0,
                 from /usr/include/bits/mman.h:45,
                 from /usr/include/sys/mman.h:41,
                 from protection_keys.c:37:
/usr/include/bits/mman-shared.h:60:5: note: previous declaration of 'pkey_set' was here
 int pkey_set (int __key, unsigned int __access_rights) __THROW;
     ^
------------

Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
Acked-by: Dave Hansen <dave.hansen@intel.com>
Signed-off-by: Shuah Khan (Samsung OSG) <shuah@kernel.org>